### ISSUE TITLE
SotG Setup

### ISSUE THREAD

**Issue by unrealkakeman89** [unrealkakeman89/sw5e#175]
- Ship Sheet
- Mod Compendia
- Deployment Compendia
- Ship Compendia
- Timmy hos VS DD coffee test

**Comment by unrealkakeman89** [comment]
Professor Bunbury has completed/working on
- Ventures item/compendia (finished)
- Working on Type A personality (in progress)
- Collapse/Expand Feature Item rows (in progress)
- Deployment item/features compendium (finished)
- Starship modifications (in progress)

**Comment by supervj** [comment]
TODO:
[] Add Starship features to NPC's
[] Link a starship back to the character since some deployment features use Starship stats
[] Add a button to update the link of actors on starships and starships on actors
[]Reference Deployment features/applicable ventures on starships crew tab to possibly make the entirety of the starship battles playable from there
[] Pretty up Crew Tab on Starships and Starship Features Tab on PC/NPCs.
[] Finish functionality of Power Dice rolls
[] Finish functionality of Regen
[x] Finish functionality of Recharge
[x] Finish functionality of Rebuild
[] add pre roll for starship hull/shield/power dice rolling
